version: "3"
services:
    database-frontend:
        build: userdata_frontend/
        depends_on:
            - 'main-project'
        ports: 
            - '3001:3000'
        stdin_open: true

    main-project:
        build: .
        ports:
            - '3000:3000'