version: "2"
services:
  practice_docker: 
    image: bbarnhi/user_info
    ports: 
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://me:!QAZxsw2d@db:5432/users
      - PORT=3000   
  db:
    image: postgres
    expose:
        - 5432
    volumes: 
        - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=!QAZxsw2
      - POSTGRES_DB=users